version: "3"
services:
  web:
    build: .
    ports:
      - "8002:3000"
    volumes:
      - .:/usr/src/app
    links:
      - db
  db:
    image: mongo
    container_name: db_container
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27020:27017"
